version: "3.9"

services:
  postgres:
    image: postgres:17
    container_name: energy-postgres-db
    environment:
      POSTGRES_USER: grujud22
      POSTGRES_PASSWORD: TH1SI8S4F3
      POSTGRES_DB: energy-db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - vibe-network

  backend:
    image: ghcr.io/grujud22/backend:latest
    container_name: energy-backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - vibe-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/energy-db
      SPRING_DATASOURCE_USERNAME: grujud22
      SPRING_DATASOURCE_PASSWORD: TH1SI8S4F3

volumes:
  postgres_data:

networks:
  vibe-network:
    driver: bridge